### ISSUE TITLE
Unblocked videos use Flash instead of HTML5

### ISSUE THREAD

**Issue by rea987** [dvcrn/ProxMate#2]
When the extension successfully unblocks a YouTube video in Germany, the video uses Flash Player instead of HTML5 player while the HTML5 trial of YouTube is activated. However, when another proxy used instead of the extension, the video  uses HTML5 player (not with all other proxies).

The HTML5 trial of YouTube can be activated from here:
http://www.youtube.com/html5

Free proxies can be found in here:
http://hidemyass.com/proxy-list/

The video's page in Germany when the extension is deactivated:
http://picturf.com/i/3OJ

The video's page in Germany when the extension is activated:
http://picturf.com/i/3OK

The video's page in Germany when another proxy is used:
http://picturf.com/i/3OL

The video's page in Turkey (the extension or another proxy are not needed):
http://picturf.com/i/3OM

By the way, when that proxy is used via the extensions preferences page as "use own proxy" option, the video uses HTML5 player. The proxy:
88.85.108.16:8080

Operating System:
Ubuntu 10.10 Maverick Meerkat (32 bit)

Browser:
Firefox 11.0.0

ProxMate Version:
1.2

User Agent:
Mozilla/5.0 (X11; Ubuntu; Linux i686; rv:11.0) Gecko/20100101 Firefox/11.0

**Comment by dvcrn** [comment]
Hmm...
Tried to allow cookies in proxy config but didn't change anything.
I'm on it!

**Comment by rea987** [comment]
It seems like the issue of the proxy which is used by the extension. Because, the video may have the same issue "some" other proxies. It may be beneficial to check the proxy that ProxMate uses.

**Comment by rea987** [comment]
I found an old page which shows how to force YouTube to use HTML5 player.

http://googlesystem.blogspot.de/2010/08/watch-video-in-youtubes-html5-player.html

However, when I add &html5=True line at the end of unblocked video, the video still uses Flash Player. I tried to add that line before the &unblocked=true , and the result is the same...

Moreover, I disabled the extension and found a proxy which opens YouTube videos within the Flash Player; &html5=True option did not work either...

By the way, I installed the extension to Chromium 17.0.963.79 and again YouTube uses Flash Player instead of HTML5 player while the HTML5 Trial is activated...

**Comment by rea987** [comment]
Hi again,

I have just found an unblocked video which uses YouTube HTML5 Video Player while the HTML5 trial of YouTube is activated.

The HTML5 trial of YouTube can be activated from here:
http://www.youtube.com/html5

The video's page:
http://www.youtube.com/watch?v=O72jfzVczxQ

The video's page in Germany when the extension is deactivated:
http://picturf.com/i/3WH

The video's page in Germany when the extension and HTML5 trial are activated:
http://picturf.com/i/3WI

The video's page in Germany when the extension is activated and the HTML5 trial is disabled:
http://picturf.com/i/3WJ

However, the previous video that I showed keeps using Flash Player while the HTML5 trial is activated.

That video's page:
http://www.youtube.com/watch?v=lzlAgD41sEg

The video's page in Germany when the extension and HTML5 trial are activated:
http://picturf.com/i/3WK

By the way, I use DownloadHelper extension the get the download URLs of the videos. If the HTML5 Trial is activated and the video supports, DownloadHelper shows the download URL of both webm, mp4 and flv versions of the video. I am pretty sure that YouTube shows the version of the video according to the User Agent of the browser.

Let's try with a "non-blocked" video for Germany.

The video's page:
http://www.youtube.com/watch?v=JOnbRwAXFF0

Download URLs which are presented by DownloalHelper:
http://picturf.com/i/3WL

Then, I tried the same with the unblocked video which I referred in the beginning:
http://picturf.com/i/3WM

As it seems, the webm URL of the video has correctly appeared and that is why the browser could use the HTML5 player.

But, I tried that with another unblocked video which still uses Flash Player and the DownloadHelper shows something like that:
http://picturf.com/i/3WN

As it is proven; if there is no webm URL, Firefox uses Flash Player to play flv files.

Lastly, I try to open it with ProxMate's "Use own Proxy" option and bingo! The video uses HTML5 player and webm URL has appeared in DownloadHelper's menu.

http://picturf.com/i/3WO

Proxy Url: 193.107.168.26
Proxy Port: 8080

Operating System:
Ubuntu 10.10 Maverick Meerkat (32 bit)

Browser:
Firefox 11.0.0

ProxMate Version:
1.3.1

DownloadHelper Version:
4.9.9

User Agent:
Mozilla/5.0 (X11; Ubuntu; Linux i686; rv:11.0) Gecko/20100101 Firefox/11.0

That's all for now. I hope the proxy which is used by ProxMate will have full HTML5 video support. Thanks!

**Comment by rea987** [comment]
It has been a while since I contributed information for the case. Is there any development in HTML5 video support for unblocked YouTube videos?

**Comment by dvcrn** [comment]
Apologies for the late reply. 
I'm still looking for an solution for this. Hope to fix it before the next release!

**Comment by jomo** [comment]
I don't think this has been fixed, can you re-open?

**Comment by dvcrn** [comment]
This repo is not being updated anymore.
ProxMate is using whatever YouTube puts on it's page. I did a few tests with the new version but didn't run into this problem anymore. Can you confirm? https://github.com/dabido/proxmate-chrome

**Comment by rea987** [comment]
YouTube uses Flash or HTML5 player for the videos regarding to the region in order to show ads. If ads for HTML5 player is not available, YouTube uses Flash Player. User can force HTML5 player by using scripts or addons like YouTube Center. That usually works fine with the ProxMate on Firefox and Pale Moon.

https://github.com/YePpHa/YouTubeCenter/wiki
https://addons.mozilla.org/en-US/firefox/addon/proxmate
