### ISSUE TITLE
Hulu

### ISSUE THREAD

**Issue by guyisra** [dvcrn/ProxMate#3]
proxmate on chrome doesn't seem to work on hulu videos

**Comment by CaptnBlubber** [comment]
Can you please Post and link and steps to reproduce

**Comment by guyisra** [comment]
1. install proxmate for chrome, make sure its enabled and checked for hulu.com in the options
2. go to http://www.hulu.com/watch/364740/weird-news-snl-star-samberg-serenades-harvard-grads
3. see notice that it can't be viewed outside united states.

am I missing something?

**Comment by CaptnBlubber** [comment]
I just checked with your link and its working for me,

Make sure you have version 1.3.1 installed, Got to your video, the popup hulu is not availabe is always there just click on close.

now klick on details located under the video and in the new apearing area click on unblock (This step by step is mentioned in the release notes aswell).

Now just wait till the ads finish (We cant skip the ads sorry) and enjoy.

**Comment by dvcrn** [comment]
The current problem on firefox is that mozilla still didn't review 1.3.1 yet. Means the version in the Firefox store is not the current one. 

If you're using Firefox, download it here - https://addons.mozilla.org/en-US/firefox/addon/proxmate/versions/
Hope that helps.

**Comment by guyisra** [comment]
solved... that weird unblock link is stupid..

**Comment by dvcrn** [comment]
Great to hear! :)
Due to technical restrictions we can't add a auto unblock right when you browse the video.

There is sadly no way to figure out if the current video is blocked or not. If you have suggestions on this, feel free to share.

**Comment by dvcrn** [comment]
Unblock link is gone. Hulu should work auto now
