### ISSUE TITLE
request - add spotify and pandora support

### ISSUE THREAD

**Issue by guyisra** [dvcrn/ProxMate#4]

**Comment by dvcrn** [comment]
Hey!
What do you mean by "Spotify Support"? 
Pandora is a little tricky to unblock but we will see if we can do anything :)

**Comment by guyisra** [comment]
for spotfiy.com

both pandora and spotify are for US only. 
note that pandora works with something like ultrasurf
thanks :)

**Comment by CaptnBlubber** [comment]
Spotify is an self running application thus not able for a browser plugin, the free Version also has to run over proxy at anytime, else Spotify detects "travel mode" wich can only be accessed in free.

**Comment by dvcrn** [comment]
pandora.com is implemented in the newest chrome build. firefox will follow soon!
