### ISSUE TITLE
Proxmateserver blocked by EMI

### ISSUE THREAD

**Issue by ghost** [dvcrn/ProxMate#6]
http://www.youtube.com/watch?v=jddSCBdjWSQ
1. GEMA Notice
2. Proxmate relink
3. EMI Notice

Edit:
Tested -> Chrome Plugin

**Comment by CaptnBlubber** [comment]
Not our Server is Blocked, the video is blocked in United States. Ive tried with severall other USA Proxys all giving me video blocked. Use a personal proxy from another state to view this video.
