### ISSUE TITLE
No longer working on Youtube

### ISSUE THREAD

**Issue by ghost** [dvcrn/ProxMate#7]
No longer working on this youtube urls:

http://www.youtube.com/watch?v=TGbwL8kSpEk
https://www.youtube.com/watch?v=eNzenkoeJcY
https://www.youtube.com/watch?v=dVFdeQh6GQ0

**Comment by CaptnBlubber** [comment]
All 3 Working for me.

**Comment by ghost** [comment]
Thanks for your help, I hope it was not to exhausting for you...

**Comment by dvcrn** [comment]
What exactly is not working? 
Do you get a proxmate error message?

**Comment by ghost** [comment]
These don't work for me either.  It says 'An error occurred.  Please try again later.', and I get a 403 Forbidden for the video files.

**Comment by dvcrn** [comment]
Youtube support is currently dead due to an youtube update.
Not sure when it'll be back

**Comment by aguenther** [comment]
I guess you have no choice but download the entire video through the proxy. Maybe proxmate could read a public proxy list and try to use random servers from there if you want to save the traffic of your own server.

**Comment by dvcrn** [comment]
Works in the newest chrome version again. 
Firefox will come soon!

I personally don't like to use public servers. You don't have control in what they read + they are most of the time veeeeery slow. 
As long as it's not getting too expensive, I don't want to do that.
